name: MoreHearts
version: 2.4.0
Description: More <3's
main: com.sqeegie.mh.MoreHearts
Author: roei12, Sqeegie
commands:
 mh:
  description: Everything =O
 morehearts:
  description: Everything =O (but longer)
 hearts:
  description: useful if HideHearts is off.