name: MoreHearts
version: 2.4.2
Description: Adds more <3's.
main: com.sqeegie.mh.MoreHearts
Author: roei12, Sqeegie
commands:
 mh:
  description: Shows all available commands.
  aliases: morehearts
 hearts:
  description: Displays the current health of a player - Useful if HideHearts is off.
  aliases: h