name: MoreHearts
version: 2.4.3
Description: Adds the ability to set custom hearts/health amounts for each player.
main: com.sqeegie.mh.MoreHearts
Author: roei12, Sqeegie
commands:
 hearts:
  description: Displays the amount of hearts you currently have. (Useful if HideHearts is enabled.)
  aliases: h
 morehearts:
  description: Displays a list with all available commands.
  aliases: mh